<<<<<<< HEAD
/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2019-12-27 05:50:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.item;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.*;

public final class itemView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1577424508066L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1577403049179L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\n");
      out.write("   \n");
      out.write("   \n");
      out.write("   ");
 
   		//로그인한 경우
   		Member memberLoggedIn= (Member)session.getAttribute("memberLoggedIn");
   		
   
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <title>re:flex</title>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR:100,300,400,500,700,900&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Libre+Barcode+128+Text|Monoton|Permanent+Marker|Righteous|Seymour+One|Stalinist+One&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\"> <!-- 부트스트랩 -->\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/mypage.css\" rel=\"stylesheet\">\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.4.1.js\"></script>\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/header.js\"></script>\n");
      out.write("    \n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <header class=\"container-fluid navbar-fixed-top\">\n");
      out.write("        <div id=\"header-wrapper\" class=\"row\">\n");
      out.write("            <div id=\"logo\" class=\"col-md-4\">\n");
      out.write("                <h1 class=\"eng\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">re:flex</a></h1>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"search\" class=\"col-md-4\">\n");
      out.write("                <h2 class=\"sr-only\">상품 검색</h2>\n");
      out.write("                <form action=\"\">\n");
      out.write("                    <button type=\"submit\" id=\"btn-search\" aria-label=\"search products\">\n");
      out.write("                        <span class=\"glyphicon glyphicon-search\" aria-hidden=\"true\"></span>\n");
      out.write("                    </button>\n");
      out.write("                    <input type=\"search\" name=\"search\" placeholder=\"검색\">\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"menu\" class=\"col-md-4\">\n");
      out.write("                <ul class=\"list-unstyled list-inline text-right\">\n");
      out.write("                    <!-- 로그인시 li.login-hide안보이게 하고 li.login-show 보이게 -->\n");
      out.write("                    ");
if(memberLoggedIn==null){ 
      out.write("\n");
      out.write("                    <li class=\"login-hide\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberLogin\">로그인</a></li>\n");
      out.write("                    <li class=\"login-hide\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberEnroll\">회원가입</a></li>\n");
      out.write("                    ");
}
                    else{
                    
      out.write("\n");
      out.write("                    <li>\n");
      out.write("\t\t\t\t\t\t");
      out.print(memberLoggedIn.getMemberName() );
      out.write("님, 안녕하세요.\n");
      out.write("                    \n");
      out.write("                    </li>                    \n");
      out.write("                    <li>\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"로그아웃\" \n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"login-show\"\n");
      out.write("\t\t\t\t\t\t\t\t   onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/logout'\"/>             \n");
      out.write("                    </li>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\n");
      out.write("\n");
      out.write("                    <li>\n");
      out.write("                        <h2 class=\"sr-only\">장바구니</h2>\n");
      out.write("                        <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberCart\" aria-label=\"cart\"><span class=\"glyphicon glyphicon-shopping-cart\" aria-hidden=\"true\"></span></a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <button type=\"button\"  id=\"btn-sidemenu\">\n");
      out.write("                            <span class=\"glyphicon glyphicon-list\" aria-hidden=\"true\"></span>\n");
      out.write("                        </button>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("                <!-- side menu -->\n");
      out.write("                <!-- level1 -->\n");
      out.write("                <div id=\"sidemenu-closeLayer\">\n");
      out.write("                <nav id=\"level1-sidemenu\" class=\"sidemenu-wrapper\">\n");
      out.write("                    <header></header>\n");
      out.write("                    <ul class=\"list-unstyled\">\n");
      out.write("                        <li id=\"recommended\" data-target=\"#level2-recommended\"><a href=\"#\">이럴 때 빌려봐<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\n");
      out.write("                        ");
 if(memberLoggedIn != null 
						  && "admin".equals(memberLoggedIn.getMemberId())){ 
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("                        <li id=\"adminPage\" data-target=\"#level2-adminPage\"><a href=\"#\">관리자페이지<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\n");
      out.write("\t\t\t\t\t");
 }else{ 
      out.write("\n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                        <li id=\"mypage\" data-target=\"#level2-mypage\"><a href=\"#\">마이페이지<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\n");
      out.write("                        ");
} 
      out.write("\n");
      out.write("                        <li><a href=\"#\">고객서비스(FAQ)</a></li>\n");
      out.write("                        <li><a href=\"#\">re:flex 소개</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("                <!-- level2: 이럴때빌려봐 -->\n");
      out.write("                <nav id=\"level2-recommended\" class=\"sidemenu-wrapper\">\n");
      out.write("                    <header class=\"text-center\">\n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\n");
      out.write("                        \t<span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\n");
      out.write("                              이럴 때 빌려봐\n");
      out.write("                        </button>\n");
      out.write("                    </header>\n");
      out.write("                    <ul class=\"list-unstyled\">\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList\">반려동물과 함께 할 때</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT02\">육아할 때</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList\">파티할 때</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList\">운동할 때</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList\">여행갈 때</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList\">캠핑갈 때</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("                <!-- level2: 마이페이지 / 로그인 안했으면 경고창 -->\n");
      out.write("                \n");
      out.write("                <nav id=\"level2-mypage\" class=\"sidemenu-wrapper\">\n");
      out.write("                    <header class=\"text-center\">\n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\n");
      out.write("                            <span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\n");
      out.write("                            마이페이지\n");
      out.write("                        </button>\n");
      out.write("                    </header>\n");
      out.write("                    \n");
      out.write("                    <ul class=\"list-unstyled\">\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageOrderList\">주문조회</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageWishlist\">위시리스트</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageRentalIng\">계약중인 렌탈</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageRentalFin\">종료중인 렌탈</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypagePoint\">포인트 확인</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageReview\">이용후기 내역</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageOneToOne\">1:1문의 내역</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberUpdate\">회원정보 수정</a></li>\n");
      out.write("                        <li><a href=\"\">회원정보 탈퇴</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("                <nav id=\"level2-adminPage\" class=\"sidemenu-wrapper\">\n");
      out.write("                    <header class=\"text-center\">\n");
      out.write("                    \n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\n");
      out.write("                            <span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\n");
      out.write("                            관리자페이지\n");
      out.write("                        </button>\n");
      out.write("                    </header>\n");
      out.write("                    <ul class=\"list-unstyled\">\n");
      out.write("                        <li><a href=\"#\">상품관리</a></li>\n");
      out.write("                        <li><a href=\"#\">주문관리</a></li>\n");
      out.write("                        <li><a href=\"#\">회원관리</a></li>\n");
      out.write("                 \n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("                \n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </header>");
      out.write("\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/itemView.js\"></script>\n");
      out.write("<!-- page nav -->\n");
      out.write("<nav class=\"line-style page-nav\">\n");
      out.write("    <ul class=\"list-unstyled list-inline\">\n");
      out.write("        <li class=\"go-home\">\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">메인</a>\n");
      out.write("            <span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"go-boxmenu\">\n");
      out.write("            <a href=\"\">이럴 때 빌려봐</a>\n");
      out.write("            <span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span>\n");
      out.write("        </li>\n");
      out.write("        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList\">반려동물</a><span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></li>\n");
      out.write("        <li>요요플러스 6+ A형(기본형) 블랙프레임(에어프랑스블루)</li>\n");
      out.write("    </ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<div id=\"view-details\" class=\"container-fluid contents none-nav\">\n");
      out.write("\t<!-- 상단: 이미지/옵션 영역 -->\n");
      out.write("\t<div id=\"view-wrapper\" class=\"row\">\n");
      out.write("\t    <section id=\"view-img\" class=\"col-md-6\">\n");
      out.write("\t        <h2 class=\"sr-only\">상품 이미지 보기</h2>\n");
      out.write("\t        <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/view-img1.jfif\" alt=\"\">\n");
      out.write("\t        <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/view-img2.jfif\" alt=\"\">\n");
      out.write("\t        <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/view-img3.jfif\" alt=\"\">\n");
      out.write("\t        <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/view-img4.jfif\" alt=\"\">\n");
      out.write("\t    </section>            \n");
      out.write("\t    <section id=\"opt-wrapper\" class=\"col-md-6\">\n");
      out.write("\t        <div id=\"opt-header\" class=\"row\">\n");
      out.write("\t            <div class=\"col-md-6\">\n");
      out.write("\t                <p id=\"total-price\" class=\"text-center\">28,490원</p>\n");
      out.write("\t            </div>\n");
      out.write("\t            <div class=\"col-md-6\">\n");
      out.write("\t                <!-- 위시리스트 페이지로 이동하겠냐는 알림창 띄우기 -->\n");
      out.write("\t                <button type=\"button\" id=\"btn-wishlist\" class=\"center-block\">\n");
      out.write("\t                    위시리스트에 담기<span class=\"glyphicon glyphicon-heart-empty\" aria-hidden=\"true\"></span>\n");
      out.write("\t                </button>\n");
      out.write("\t            </div>\n");
      out.write("\t        </div>\n");
      out.write("\t        <section id=\"opt-inner\">\n");
      out.write("\t            <section>\n");
      out.write("\t                <p class=\"pbrand\">BABYZEN</p>\n");
      out.write("\t                <p id=\"pname\">요요플러스 6+ A형(기본형) 블랙프레임(에어프랑스블루)</p>\n");
      out.write("\t            </section>\n");
      out.write("\t            <section id=\"sel-rentType\">\n");
      out.write("\t                <p>렌탈옵션</p>\n");
      out.write("\t                <label for=\"rent-type\" class='sr-only'>렌탈옵션</label>\n");
      out.write("\t                <select name=\"rentType\" id=\"rent-type\">\n");
      out.write("\t                    <option value=\"7\"><span class=\"rt-price\">28,490</span>원 <span class=\"period\">(일시납 7일)</option>\n");
      out.write("\t                    <option value=\"14\"><span class=\"rt-price\">28,490</span>원 <span class=\"period\">(일시납 14일)</option>\n");
      out.write("\t                    <option value=\"30\"><span class=\"rt-price\">45,600</span>원 <span class=\"period\">(일시납 30일)</option>\n");
      out.write("\t                </select>\n");
      out.write("\t            </section>\n");
      out.write("\t            <section id=\"sel-amount\">\n");
      out.write("\t                <p>수량</p>\n");
      out.write("\t                <label for=\"\" class=\"sr-only\">구매수량</label>\n");
      out.write("\t                <button type=\"button\" class=\"btn-minus\"><span class=\"glyphicon glyphicon-minus\" aria-hidden=\"true\"></span></button>\n");
      out.write("\t                <input type=\"text\" name=\"orderNo\" id=\"orderNo\" class=\"text-center\" value=\"1\" disabled>\n");
      out.write("\t                <button type=\"button\" class=\"btn-plus\"><span class=\"glyphicon glyphicon-plus\" aria-hidden=\"true\"></span></button>\n");
      out.write("\t            </section>\n");
      out.write("\t            <div id=\"opt-footer\" class=\"row\">\n");
      out.write("\t                <div class=\"col-md-6\">\n");
      out.write("\t                    <!-- 장바구니 페이지로 이동하겠냐는 알림창 띄우기 -->\n");
      out.write("\t                    <button type=\"button\" id=\"btn-addCart\" class=\"center-block\">장바구니</button>\n");
      out.write("\t                </div>\n");
      out.write("\t                <div class=\"col-md-6\">\n");
      out.write("\t                    <button type=\"button\" id=\"btn-goRent\" class=\"center-block\">바로렌탈</button>\n");
      out.write("\t                </div>\n");
      out.write("\t            </div>\n");
      out.write("\t        </section>\n");
      out.write("\t    </section>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- 하단: 상품상세/리뷰/qna 영역 -->\n");
      out.write("\t<div id=\"details-wrapper\">\n");
      out.write("\t    <section class=\"details-tab\">\n");
      out.write("\t        <ul class=\"list-unstyled list-inline row\">\n");
      out.write("\t            <li class=\"col-md-3 active\"><button type=\"button\" onclick=\"showContent(this, 'details-img')\">상품상세</button></li>\n");
      out.write("\t            <li class=\"col-md-3\"><button type=\"button\" onclick=\"showContent(this, 'details-infoShip');\">배송/반품</button></li>\n");
      out.write("\t            <li class=\"col-md-3\"><button type=\"button\" onclick=\"showContent(this, 'details-review');\">이용후기(<span class=\"board-cnt\">10</span>)</button></li>\n");
      out.write("\t            <li class=\"col-md-3\"><button type=\"button\" onclick=\"showContent(this, 'details-qna');\">상품Q&A(<span class=\"board-cnt\">10</span>)</button></li>\n");
      out.write("\t        </ul>\n");
      out.write("\t    </section>\n");
      out.write("\t    <div class=\"details-contents row\">\n");
      out.write("\t        <div class=\"col-md-1\"></div>\n");
      out.write("\t        <div class=\"col-md-10 dc-inner\">\n");
      out.write("\t            <!-- 상품상세 -->\n");
      out.write("\t            <section id=\"details-img\" class=\"active\">\n");
      out.write("\t                <h3 class=\"sr-only\">상품상세이미지</h3>\n");
      out.write("\t                <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/item-detail.png\" alt=\"\">\n");
      out.write("\t            </section>\n");
      out.write("\t            <!-- 배송반품 -->\n");
      out.write("\t            <section id=\"details-infoShip\">\n");
      out.write("\t                <p>배송반품</p>\n");
      out.write("\t            </section>\n");
      out.write("\t            <!-- 이용후기 -->\n");
      out.write("\t            <section id=\"details-review\">\n");
      out.write("\t                <section id=\"writed-review\" class=\"list-wrapper\">\n");
      out.write("\t                    <h3 class=\"sr-only\">이용후기 리스트</h3>\n");
      out.write("\t                    <ul class=\"list-unstyled wishlist-inner\">\n");
      out.write("\t                        <li>\n");
      out.write("\t                            <section class=\"dtReview-header\">\n");
      out.write("\t                                <div class=\"star pull-left\">\n");
      out.write("\t                                    <span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>\n");
      out.write("\t                                    <span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>\n");
      out.write("\t                                    <span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>\n");
      out.write("\t                                    <span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>\n");
      out.write("\t                                    <span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>\n");
      out.write("\t                                </div>\n");
      out.write("\t                                <div class=\"review-info pull-right\">\n");
      out.write("\t                                    <span class=\"review-writer\">uj9208</span>\n");
      out.write("\t                                    <span class=\"review-slash\"> | </span>\n");
      out.write("\t                                    <span class=\"review-date\">2019.12.22</span>\n");
      out.write("\t                                </div>\n");
      out.write("\t                            </section>\n");
      out.write("\t                            <section class=\"review-content\">\n");
      out.write("\t                                <div>\n");
      out.write("\t                                    <p>dolor voluptates delectus nemo voluptatem quam nisi impedit es delectus nemo voluptatem quam nisi impe ipsa minus unde, aliquam est? At sapiente necessitatibus corporis beatae?</p>\n");
      out.write("\t                                </div>\n");
      out.write("\t                                <div class=\"reviewImg-wrapper row\">\n");
      out.write("\t                                    <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/view-img1.jfif\" class=\"col-md-3\" alt=\"\">\n");
      out.write("\t                                    <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/view-img2.jfif\" class=\"col-md-3\" alt=\"\">\n");
      out.write("\t                                    <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/view-img3.jfif\" class=\"col-md-3\" alt=\"\">\n");
      out.write("\t                                </div>\n");
      out.write("\t                            </section>\n");
      out.write("\t                        </li>\n");
      out.write("\t                        <li>\n");
      out.write("\t                            <section class=\"dtReview-header\">\n");
      out.write("\t                                <div class=\"star pull-left\">\n");
      out.write("\t                                    <span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>\n");
      out.write("\t                                    <span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>\n");
      out.write("\t                                    <span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>\n");
      out.write("\t                                    <span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>\n");
      out.write("\t                                    <span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>\n");
      out.write("\t                                </div>\n");
      out.write("\t                                <div class=\"review-info pull-right\">\n");
      out.write("\t                                    <span class=\"review-writer\">uj9208</span>\n");
      out.write("\t                                    <span class=\"review-slash\"> | </span>\n");
      out.write("\t                                    <span class=\"review-date\">2019.12.22</span>\n");
      out.write("\t                                </div>\n");
      out.write("\t                            </section>\n");
      out.write("\t                            <section class=\"review-content\">\n");
      out.write("\t                                <div>\n");
      out.write("\t                                    <p>dolor voluptates delectus nemo voluptatem quam nisi impedit es delectus nemo voluptatem quam nisi impe ipsa minus unde, aliquam est? At sapiente necessitatibus corporis beatae?</p>\n");
      out.write("\t                                </div>\n");
      out.write("\t                                <div class=\"reviewImg-wrapper row\">\n");
      out.write("\t                                    <!-- <img src=\"images/view-img1.jfif\" class=\"col-md-3\" alt=\"\">\n");
      out.write("\t                                    <img src=\"images/view-img2.jfif\" class=\"col-md-3\" alt=\"\">\n");
      out.write("\t                                    <img src=\"images/view-img3.jfif\" class=\"col-md-3\" alt=\"\"> -->\n");
      out.write("\t                                </div>\n");
      out.write("\t                            </section>\n");
      out.write("\t                        </li>\n");
      out.write("\t                    </ul>\n");
      out.write("\t                </section>\n");
      out.write("\t                <!-- 페이징바 -->\n");
      out.write("\t                <nav class=\"paging-bar text-center\">\n");
      out.write("\t                    <ul class=\"list-unstyled list-inline\">\n");
      out.write("\t                    <li>\n");
      out.write("\t                        <a href=\"#\" aria-label=\"Previous\">\n");
      out.write("\t                            <span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\n");
      out.write("\t                        </a>\n");
      out.write("\t                    </li>\n");
      out.write("\t                    <li class=\"cPage\"><a href=\"#\">1</a></li>\n");
      out.write("\t                    <li><a href=\"#\">2</a></li>\n");
      out.write("\t                    <li><a href=\"#\">3</a></li>\n");
      out.write("\t                    <li><a href=\"#\">4</a></li>\n");
      out.write("\t                    <li><a href=\"#\">5</a></li>\n");
      out.write("\t                    <li>\n");
      out.write("\t                        <a href=\"#\" aria-label=\"Next\">\n");
      out.write("\t                            <span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span>\n");
      out.write("\t                        </a>\n");
      out.write("\t                    </li>\n");
      out.write("\t                    </ul>\n");
      out.write("\t                </nav>\n");
      out.write("\t            </section>\n");
      out.write("\t            <!-- 상품QNA -->\n");
      out.write("\t            <section id=\"details-qna\">\n");
      out.write("\t                <div class=\"btn-wrapper\">\n");
      out.write("\t                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemQnaForm\" class=\"btn-radius\">문의하기</a>\n");
      out.write("\t                </div>\n");
      out.write("\t                <section id=\"point-list\" class=\"list-wrapper\">\n");
      out.write("\t                    <h3 class=\"sr-only\">문의내역 리스트</h3>\n");
      out.write("\t                    <table class=\"text-center list-tbl\">\n");
      out.write("\t                        <thead>\n");
      out.write("\t                            <tr class=\"row\">\n");
      out.write("\t                                <th class=\"col-md-6 text-center\">문의내용</th>\n");
      out.write("\t                                <th class=\"col-md-2 text-center\">답변상태</th>\n");
      out.write("\t                                <th class=\"col-md-2 text-center\">작성자</th>\n");
      out.write("\t                                <th class=\"col-md-2 text-center\">작성일</th>\n");
      out.write("\t                            </tr>\n");
      out.write("\t                        </thead>\n");
      out.write("\t                        <tbody>\n");
      out.write("\t                            <tr class=\"row qna-header\">\n");
      out.write("\t                                <td class=\"col-md-6 qna-title\">\n");
      out.write("\t                                    <button type=\"button\" class=\"center-block\">오늘 출고 되나요?어제 주문했는데 아직 배송준비중이네요..금요일에 써야하는거라 안돼면 취소해야해서요</button>\n");
      out.write("\t                                </td>\n");
      out.write("\t                                <td class=\"col-md-2\">답변완료</td>\n");
      out.write("\t                                <td class=\"col-md-2\">uj9208</td>\n");
      out.write("\t                                <td class=\"col-md-2\">2019.12.22</td>\n");
      out.write("\t                            </tr>\n");
      out.write("\t                            <tr class=\"row qna-view\">\n");
      out.write("\t                                <td colspan=\"4\" class=\"col-md-12\">\n");
      out.write("\t                                    <div class=\"q-wrapper\">\n");
      out.write("\t                                        <span class=\"q-title strong\">Q.</span>\n");
      out.write("\t                                        <p class=\"center-block\">오늘 출고 되나요?어제 주문했는데 아직 배송준비중이네요..금요일에 써야하는거라 안돼면 취소해야해서요</p>\n");
      out.write("\t                                    </div>\n");
      out.write("\t                                    <div class=\"q-wrapper\">\n");
      out.write("\t                                        <span class=\"q-title strong\">A.</span>\n");
      out.write("\t                                        <p class=\"center-block\">\n");
      out.write("\t                                            안녕하세요, 고객님. 라이프스타일을 렌탈하다. 롯데렌탈 MYOMEE(묘미)입니다.\n");
      out.write("\t                                            먼저 묘미를 이용해주셔서 감사하다는 말씀을 드립니다.\n");
      out.write("\t                                            <br><br><br>\n");
      out.write("\t                                            문의주신 상품은 당일 출고되며, 배송은 출고일부터 영업일 기준(주말 및 공휴일 제외) 1~2일 가량 소요됩니다.\n");
      out.write("\t                                            다만, 출고 및 배송 일정은 배송지역 및 택배사 물류 사정 등 특이사항에 따라 달라질 수 있음을 양해 부탁드립니다.\n");
      out.write("\t                                        </p>\n");
      out.write("\t                                    </div>\n");
      out.write("\t                                </td>\n");
      out.write("\t                            </tr>\n");
      out.write("\t                            <tr class=\"row qna-header\">\n");
      out.write("\t                                <td class=\"col-md-6 qna-title\">\n");
      out.write("\t                                    <button type=\"button\" class=\"center-block\">오늘 출고 되나요?어제 주문했는데 아직 배송준비중이네요..금요일에 써야하는거라 안돼면 취소해야해서요</button>\n");
      out.write("\t                                </td>\n");
      out.write("\t                                <td class=\"col-md-2\">답변대기</td>\n");
      out.write("\t                                <td class=\"col-md-2\">uj9208</td>\n");
      out.write("\t                                <td class=\"col-md-2\">2019.12.22</td>\n");
      out.write("\t                            </tr>\n");
      out.write("\t                            <tr class=\"row qna-view\">\n");
      out.write("\t                                <td colspan=\"4\" class=\"col-md-12\">\n");
      out.write("\t                                    <div class=\"q-wrapper\">\n");
      out.write("\t                                        <span class=\"q-title strong\">Q.</span>\n");
      out.write("\t                                        <p class=\"center-block\">오늘 출고 되나요?어제 주문했는데 아직 배송준비중이네요..금요일에 써야하는거라 안돼면 취소해야해서요</p>\n");
      out.write("\t                                    </div>\n");
      out.write("\t                                    <div class=\"q-wrapper\">\n");
      out.write("\t                                        <span class=\"q-title strong\">A.</span>\n");
      out.write("\t                                        <p class=\"center-block\">\n");
      out.write("\t                                            답변 대기중\n");
      out.write("\t                                        </p>\n");
      out.write("\t                                    </div>\n");
      out.write("\t                                </td>\n");
      out.write("\t                            </tr>\n");
      out.write("\t                        </tbody>\n");
      out.write("\t                    </table>\n");
      out.write("\t                </section>\n");
      out.write("\t                <!-- 페이징바 -->\n");
      out.write("\t                <nav class=\"paging-bar text-center\">\n");
      out.write("\t                    <ul class=\"list-unstyled list-inline\">\n");
      out.write("\t                        <li>\n");
      out.write("\t                            <a href=\"#\" aria-label=\"Previous\">\n");
      out.write("\t                                <span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\n");
      out.write("\t                            </a>\n");
      out.write("\t                        </li>\n");
      out.write("\t                        <li class=\"cPage\"><a href=\"#\">1</a></li>\n");
      out.write("\t                        <li><a href=\"#\">2</a></li>\n");
      out.write("\t                        <li><a href=\"#\">3</a></li>\n");
      out.write("\t                        <li><a href=\"#\">4</a></li>\n");
      out.write("\t                        <li><a href=\"#\">5</a></li>\n");
      out.write("\t                        <li>\n");
      out.write("\t                            <a href=\"#\" aria-label=\"Next\">\n");
      out.write("\t                                <span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span>\n");
      out.write("\t                            </a>\n");
      out.write("\t                        </li>\n");
      out.write("\t                    </ul>\n");
      out.write("\t                </nav>\n");
      out.write("\t            </section>\n");
      out.write("\t        </div>\n");
      out.write("\t        <div class=\"col-md-1\"></div>\n");
      out.write("\t    </div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<footer class=\"container-fluid\">\n");
      out.write("\t    <div class=\"line-style\"></div>\n");
      out.write("\t    <!-- first line -->\n");
      out.write("\t    <div id=\"footer-menu\" class=\"row\">\n");
      out.write("\t        <div class=\"col-md-3\">\n");
      out.write("\t            <header>회사소개</header>\n");
      out.write("\t            <ul class=\"list-unstyled\">\n");
      out.write("\t                <li><a href=\"#\">이용약관</a></li>\n");
      out.write("\t                <li><a href=\"#\">정책안내</a></li>\n");
      out.write("\t            </ul>\n");
      out.write("\t        </div>\n");
      out.write("\t        <div class=\"col-md-3\">\n");
      out.write("\t            <header>고객서비스</header>\n");
      out.write("\t            <ul class=\"list-unstyled\">\n");
      out.write("\t                <li><a href=\"#\">FAQ</a></li>\n");
      out.write("\t                <li><a href=\"#\">1:1문의</a></li>\n");
      out.write("\t                <li><a href=\"#\">주문현황</a></li>\n");
      out.write("\t            </ul>\n");
      out.write("\t        </div>\n");
      out.write("\t        <div class=\"col-md-3\">\n");
      out.write("\t            <header>문의하기</header>\n");
      out.write("\t            <p id=\"q-call\" class=\"lead\">1577-1577</p>\n");
      out.write("\t            <p id=\"q-email\" class=\"lead\">reflex@naver.com</p>\n");
      out.write("\t            <p>평일 10:00~18:00</p>\n");
      out.write("\t            <p>주말 및 공휴일 휴무</p>\n");
      out.write("\t        </div>\n");
      out.write("\t        <div class=\"col-md-3\">\n");
      out.write("\t            <header>SNS</header>\n");
      out.write("\t            <ul class=\"list-unstyled\">\n");
      out.write("\t                <li><a href=\"#\">Facebook</a></li>\n");
      out.write("\t                <li><a href=\"#\">Instagram</a></li>\n");
      out.write("\t                <li><a href=\"#\">Twitter</a></li>\n");
      out.write("\t            </ul>\n");
      out.write("\t        </div>\n");
      out.write("\t    </div>\n");
      out.write("\t    <!-- second line -->\n");
      out.write("\t    <div id=\"about\" class=\"row\">\n");
      out.write("\t        <p class=\"eng\">re:flex</p>\n");
      out.write("\t        <p>대표:유찬호<span class=\"bar\"></span>사업자등록번호:419-87-00807<span class=\"bar\"></span>통신판매업신고:제 2017-서울마포-2273호</p>\n");
      out.write("\t        <p>주소: 서울특별시 마포구 동교동 203-43 4층<span class=\"bar\"></span>대표전화:1566-6813<span class=\"bar\"></span>FAX:070-7848-0818<span class=\"bar\"></span>이메일:reflex@naver.com</p>\n");
      out.write("\t        <p>개인정보관리책임자:유찬호</p>\n");
      out.write("\t    </div>\n");
      out.write("\t    <div id=\"copyright\" class=\"line-style\"><span>ⓒ</span>2019 re:flex</div>\n");
      out.write("\t</footer>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
=======
/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2019-12-29 18:25:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.item;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import item.model.vo.ItemQnaAns;
import java.util.Map;
import item.model.vo.ItemQna;
import item.model.vo.ItemImage;
import java.util.List;
import item.model.vo.Item;
import java.text.DecimalFormat;
import member.model.vo.*;

public final class itemView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1577639837852L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1577465951749L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("item.model.vo.ItemImage");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("item.model.vo.Item");
    _jspx_imports_classes.add("item.model.vo.ItemQnaAns");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("item.model.vo.ItemQna");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
	//로그인한 경우
	Member memberLoggedIn= (Member)session.getAttribute("memberLoggedIn");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>re:flex</title>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR:100,300,400,500,700,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Libre+Barcode+128+Text|Monoton|Permanent+Marker|Righteous|Seymour+One|Stalinist+One&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\"> <!-- 부트스트랩 -->\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/mypage.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.4.1.js\"></script>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/header.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header class=\"container-fluid navbar-fixed-top\">\r\n");
      out.write("        <div id=\"header-wrapper\" class=\"row\">\r\n");
      out.write("            <div id=\"logo\" class=\"col-md-4\">\r\n");
      out.write("                <h1 class=\"eng\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">re:flex</a></h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"search\" class=\"col-md-4\">\r\n");
      out.write("                <h2 class=\"sr-only\">상품 검색</h2>\r\n");
      out.write("                <form action=\"\">\r\n");
      out.write("                    <button type=\"submit\" id=\"btn-search\" aria-label=\"search products\">\r\n");
      out.write("                        <span class=\"glyphicon glyphicon-search\" aria-hidden=\"true\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <input type=\"search\" name=\"search\" placeholder=\"검색\">\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"menu\" class=\"col-md-4\">\r\n");
      out.write("                <ul class=\"list-unstyled list-inline text-right\">\r\n");
      out.write("                    ");
if(memberLoggedIn==null){ 
      out.write("\r\n");
      out.write("\t                    <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberLogin\">로그인</a></li>\r\n");
      out.write("\t                    <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberEnroll\">회원가입</a></li>\r\n");
      out.write("                    ");

                    	}
                    	else{
                    
      out.write("\r\n");
      out.write("\t                    <li><span class=\"strong\">");
      out.print(memberLoggedIn.getMemberName());
      out.write("</span>님</li>                    \r\n");
      out.write("\t                    <li>\r\n");
      out.write("\t                    \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout\">로그아웃</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.write("             \r\n");
      out.write("\t                    </li>\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <h2 class=\"sr-only\">장바구니</h2>\r\n");
      out.write("                        <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberCart\" aria-label=\"cart\"><span class=\"glyphicon glyphicon-shopping-cart\" aria-hidden=\"true\"></span></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <button type=\"button\"  id=\"btn-sidemenu\">\r\n");
      out.write("                            <span class=\"glyphicon glyphicon-list\" aria-hidden=\"true\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <!-- side menu -->\r\n");
      out.write("                <!-- level1 -->\r\n");
      out.write("                <div id=\"sidemenu-closeLayer\">\r\n");
      out.write("                <nav id=\"level1-sidemenu\" class=\"sidemenu-wrapper\">\r\n");
      out.write("                    <header></header>\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li id=\"recommended\" data-target=\"#level2-recommended\"><a href=\"#\">이럴 때 빌려봐<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\r\n");
      out.write("                        ");
 if(memberLoggedIn != null  && "admin".equals(memberLoggedIn.getMemberId())){ 
      out.write("\r\n");
      out.write("                        \t<li id=\"adminPage\" data-target=\"#level2-adminPage\"><a href=\"#\">관리자페이지<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\r\n");
      out.write("\t\t\t\t\t\t");
 }
                        	else{ 
                        
      out.write("\r\n");
      out.write("                        \t<li id=\"mypage\" data-target=\"#level2-mypage\"><a href=\"#\">마이페이지<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/faq/faqBoard\">고객서비스(FAQ)</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/faq/faqIndex\">re:flex 소개</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <!-- level2: 이럴때빌려봐 -->\r\n");
      out.write("                <nav id=\"level2-recommended\" class=\"sidemenu-wrapper\">\r\n");
      out.write("                    <header class=\"text-center\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\r\n");
      out.write("                        \t<span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("                              이럴 때 빌려봐\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </header>\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT01\">반려동물과 함께 할 때</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT02\">육아할 때</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT03\">파티할 때</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT04\">운동할 때</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT05\">여행갈 때</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT06\">캠핑갈 때</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <!-- level2: 마이페이지 / 로그인 안했으면 경고창 -->\r\n");
      out.write("                \r\n");
      out.write("                <nav id=\"level2-mypage\" class=\"sidemenu-wrapper\">\r\n");
      out.write("                    <header class=\"text-center\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\r\n");
      out.write("                            <span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("                            마이페이지\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </header>\r\n");
      out.write("                    \r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageOrderList\">주문조회</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageWishlist\">위시리스트</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageRentalIng\">계약중인 렌탈</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageRentalFin\">종료중인 렌탈</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypagePoint\">포인트 확인</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageReview\">이용후기 내역</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageOneToOne\">1:1문의 내역</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberUpdate\">회원정보 수정</a></li>\r\n");
      out.write("                        <li><a href=\"\">회원정보 탈퇴</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <nav id=\"level2-adminPage\" class=\"sidemenu-wrapper\">\r\n");
      out.write("                    <header class=\"text-center\">\r\n");
      out.write("                    \r\n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\r\n");
      out.write("                            <span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("                            관리자페이지\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </header>\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li><a href=\"#\">상품관리</a></li>\r\n");
      out.write("                        <li><a href=\"#\">주문관리</a></li>\r\n");
      out.write("                        <li><a href=\"#\">회원관리</a></li>\r\n");
      out.write("                 \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>");
      out.write('\r');
      out.write('\n');

	String categoryNo = (String)request.getAttribute("categoryNo");
	Item item = (Item)request.getAttribute("item");
	List<ItemImage> imgList = (List<ItemImage>)request.getAttribute("imgList");
	List<ItemQna> qList = (List<ItemQna>)request.getAttribute("qList");
	Map<Integer, ItemQnaAns> qnaMap = (Map<Integer, ItemQnaAns>)request.getAttribute("qnaMap");
	
	//가격 콤마찍기
	int discountedPrice7 = (int)Math.ceil((item.getItemPrice()*0.98)/240*7)/100*100; //14일기준
	int discountedPrice14 = (int)Math.ceil((item.getItemPrice()*0.95)/240*14)/100*100; //14일기준
	int discountedPrice30 = (int)Math.ceil((item.getItemPrice()*0.90)/240*30)/100*100; //14일기준
	DecimalFormat dc = new DecimalFormat("###,###,###,###원");
	String price7 = dc.format(discountedPrice7);
	String price14 = dc.format(discountedPrice14);
	String price30 = dc.format(discountedPrice30);
	
	//상품설명
	String desc = item.getItemDesc();
	String[] descArray = desc.split(",");

      out.write("\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/itemView.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$('#btn-goQna').on('click', function(){\r\n");
      out.write("\t\t");

			if(memberLoggedIn==null){
		
      out.write("\r\n");
      out.write("\t\t\t\tif(!confirm(\"로그인이 필요한 서비스입니다.\\n로그인 페이지로 이동하시겠습니까?\")) return;\r\n");
      out.write("\t\t\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/member/memberLogin\";\r\n");
      out.write("\t\t");

			}
			else
		
      out.write("\r\n");
      out.write("\t\t\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/item/itemQnaForm?categoryNo=");
      out.print(categoryNo);
      out.write("&itemNo=");
      out.print(item.getItemNo());
      out.write("\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//수량버튼 클릭\r\n");
      out.write("\tchangeOrderNo();\r\n");
      out.write("});\r\n");
      out.write("function changeOrderNo(){\r\n");
      out.write("\tlet stockStr = ");
      out.print(item.getItemStock());
      out.write("-1+\"\"; //상품 재고(문자열)\r\n");
      out.write("\tlet inputOrderNo = document.querySelector(\"#orderNo\");\r\n");
      out.write("\tlet oderNoNum = inputOrderNo.value*1; //수량(정수형)\r\n");
      out.write("\tlet btnPlus = document.querySelector(\".btn-plus\");\r\n");
      out.write("\tlet btnMinus = document.querySelector(\".btn-minus\");\r\n");
      out.write("\t\r\n");
      out.write("\tbtnMinus.addEventListener('click', function(){\r\n");
      out.write("\t\tif(inputOrderNo.value===\"1\"){\r\n");
      out.write("\t\t\tthis.disabled = \"disabled\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\toderNoNum -= 1; //정수형\r\n");
      out.write("\t\tinputOrderNo.value = oderNoNum+\"\"; //문자열\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tbtnPlus.addEventListener('click', function(){\r\n");
      out.write("\t\tif(inputOrderNo.value===stockStr){\r\n");
      out.write("\t\t\tthis.disabled = \"disabled\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\toderNoNum += 1; //정수형\r\n");
      out.write("\t\tinputOrderNo.value = oderNoNum+\"\"; //문자열\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<!-- page nav -->\r\n");
      out.write("<nav class=\"line-style page-nav\">\r\n");
      out.write("    <ul class=\"list-unstyled list-inline\">\r\n");
      out.write("        <li class=\"go-home\">\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">메인</a>\r\n");
      out.write("            <span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"go-boxmenu\">\r\n");
      out.write("            <a href=\"\">이럴 때 빌려봐</a>\r\n");
      out.write("            <span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("        </li>\r\n");
      out.write("        ");
 
        	if("CT01".equals(categoryNo)){
        
      out.write("\r\n");
      out.write("        \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=");
      out.print(categoryNo);
      out.write("\">반려동물과 함께 할 때</a><span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></li>\r\n");
      out.write("        ");

        	}
        	if("CT02".equals(categoryNo)){
        
      out.write("\r\n");
      out.write("        \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=");
      out.print(categoryNo);
      out.write("\">육아할 때</a><span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></li>\r\n");
      out.write("        ");

        	}
        	if("CT03".equals(categoryNo)){
        
      out.write("\r\n");
      out.write("        \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=");
      out.print(categoryNo);
      out.write("\">파티할 때</a><span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></li>\r\n");
      out.write("        ");

        	}
        	if("CT04".equals(categoryNo)){
        
      out.write("\r\n");
      out.write("        \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=");
      out.print(categoryNo);
      out.write("\">운동할 때</a><span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></li>\r\n");
      out.write("        ");

        	}
        	if("CT05".equals(categoryNo)){
        
      out.write("\r\n");
      out.write("        \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=");
      out.print(categoryNo);
      out.write("\">여행갈 때</a><span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></li>\r\n");
      out.write("        ");

        	}
        	if("CT06".equals(categoryNo)){
        
      out.write("\r\n");
      out.write("        \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=");
      out.print(categoryNo);
      out.write("\">캠핑갈 때</a><span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></li>\r\n");
      out.write("        ");

        	}
        
      out.write("\r\n");
      out.write("        <li>");
      out.print(item.getItemName());
      out.write("</li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div id=\"view-details\" class=\"container-fluid contents none-nav\">\r\n");
      out.write("\t<!-- 상단: 이미지/옵션 영역 -->\r\n");
      out.write("\t<div id=\"view-wrapper\" class=\"row\">\r\n");
      out.write("\t    <section id=\"view-img\" class=\"col-md-6\">\r\n");
      out.write("\t        <h2 class=\"sr-only\">상품 이미지 보기</h2>\r\n");
      out.write("\t        <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/");
      out.print(categoryNo);
      out.write('/');
      out.print(imgList.get(0).getItemImageDefault() );
      out.write("\" alt=\"상품 대표이미지\">\r\n");
      out.write("\t        ");

	        	//이미지가 2개 이상이라면(서브이미지가 있다면)
				if(imgList.size()>2){
					for(int i=1; i<imgList.size()-1; i++){
	        
      out.write("\r\n");
      out.write("\t        \t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/");
      out.print(categoryNo);
      out.write('/');
      out.print(imgList.get(i).getItemImageDefault() );
      out.write("\" alt=\"상품 서브이미지\">\r\n");
      out.write("\t        ");

					}
	        	}
	        
      out.write("\r\n");
      out.write("\t    </section>            \r\n");
      out.write("\t    <section id=\"opt-wrapper\" class=\"col-md-6\">\r\n");
      out.write("\t        <div id=\"opt-header\" class=\"row\">\r\n");
      out.write("\t            <div class=\"col-md-6\">\r\n");
      out.write("\t                <p id=\"total-price\" class=\"text-center\">");
      out.print(price14);
      out.write("</p>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <div class=\"col-md-6\">\r\n");
      out.write("\t                <!-- 위시리스트 페이지로 이동하겠냐는 알림창 띄우기 -->\r\n");
      out.write("\t                <button type=\"button\" id=\"btn-wishlist\" class=\"center-block\">\r\n");
      out.write("\t                   \t 위시리스트에 담기<span class=\"glyphicon glyphicon-heart-empty\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t                </button>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <section id=\"opt-inner\">\r\n");
      out.write("\t            <section>\r\n");
      out.write("\t                <p class=\"pbrand\">");
      out.print(item.getItemBrand());
      out.write("</p>\r\n");
      out.write("\t                <p id=\"pname\">");
      out.print(item.getItemName());
      out.write("</p>\r\n");
      out.write("\t            </section>\r\n");
      out.write("\t            <section id=\"sel-rentType\">\r\n");
      out.write("\t                <p>렌탈옵션</p>\r\n");
      out.write("\t                <label for=\"rent-type\" class='sr-only'>렌탈옵션</label>\r\n");
      out.write("\t                <select name=\"rentType\" id=\"rent-type\">\r\n");
      out.write("\t                    <option value=\"7\"><span class=\"rt-price\">");
      out.print(price7);
      out.write("</span><span class=\"period\">(일시납 7일)</option>\r\n");
      out.write("\t                    <option value=\"14\" selected><span class=\"rt-price\">");
      out.print(price14);
      out.write("</span><span class=\"period\">(일시납 14일)</option>\r\n");
      out.write("\t                    <option value=\"30\"><span class=\"rt-price\">");
      out.print(price30);
      out.write("</span><span class=\"period\">(일시납 30일)</option>\r\n");
      out.write("\t                </select>\r\n");
      out.write("\t            </section>\r\n");
      out.write("\t            <section id=\"sel-amount\">\r\n");
      out.write("\t                <p>수량</p>\r\n");
      out.write("\t                <label for=\"\" class=\"sr-only\">구매수량</label>\r\n");
      out.write("\t                <button type=\"button\" class=\"btn-minus\"><span class=\"glyphicon glyphicon-minus\" aria-hidden=\"true\"></span></button>\r\n");
      out.write("\t                <input type=\"text\" name=\"orderNo\" id=\"orderNo\" class=\"text-center\" value=\"1\" disabled>\r\n");
      out.write("\t                <button type=\"button\" class=\"btn-plus\"><span class=\"glyphicon glyphicon-plus\" aria-hidden=\"true\"></span></button>\r\n");
      out.write("\t            </section>\r\n");
      out.write("\t            <div id=\"opt-footer\" class=\"row\">\r\n");
      out.write("\t                <div class=\"col-md-6\">\r\n");
      out.write("\t                    <!-- 장바구니 페이지로 이동하겠냐는 알림창 띄우기 -->\r\n");
      out.write("\t                    <button type=\"button\" id=\"btn-addCart\" class=\"center-block\">장바구니</button>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <div class=\"col-md-6\">\r\n");
      out.write("\t                    <button type=\"button\" id=\"btn-goRent\" class=\"center-block\">바로렌탈</button>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <section id=\"opt-desc\">\r\n");
      out.write("\t            \t<p>제품 고시 정보</p>\r\n");
      out.write("\t            \t<ul class=\"list-unstyled\">\r\n");
      out.write("\t            \t");

	            		for(String str: descArray){	
	            	
      out.write("\r\n");
      out.write("\t            \t\t<li>");
      out.print(str);
      out.write("</li>\r\n");
      out.write("\t            \t");

	            		}
	            	
      out.write("\r\n");
      out.write("\t            \t</ul>\r\n");
      out.write("\t            </section>\r\n");
      out.write("\t        </section>\r\n");
      out.write("\t    </section>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 하단: 상품상세/리뷰/qna 영역 -->\r\n");
      out.write("\t<div id=\"details-wrapper\">\r\n");
      out.write("\t    <section class=\"details-tab\">\r\n");
      out.write("\t        <ul class=\"list-unstyled list-inline row\">\r\n");
      out.write("\t            <li class=\"col-md-3 active\"><button type=\"button\" onclick=\"showContent(this, 'details-img')\">상품상세</button></li>\r\n");
      out.write("\t            <li class=\"col-md-3\"><button type=\"button\" onclick=\"showContent(this, 'details-infoShip');\">배송/반품</button></li>\r\n");
      out.write("\t            <li class=\"col-md-3\"><button type=\"button\" onclick=\"showContent(this, 'details-review');\">이용후기(<span class=\"board-cnt\">10</span>)</button></li>\r\n");
      out.write("\t            <li class=\"col-md-3\"><button type=\"button\" onclick=\"showContent(this, 'details-qna');\">상품Q&A(<span class=\"board-cnt\">10</span>)</button></li>\r\n");
      out.write("\t        </ul>\r\n");
      out.write("\t    </section>\r\n");
      out.write("\t    <div class=\"details-contents row\">\r\n");
      out.write("\t        <div class=\"col-md-1\"></div>\r\n");
      out.write("\t        <div class=\"col-md-10 dc-inner\">\r\n");
      out.write("\t            <!-- 상품상세 -->\r\n");
      out.write("\t            <section id=\"details-img\" class=\"active\">\r\n");
      out.write("\t                <h3 class=\"sr-only\">상품상세이미지</h3>\r\n");
      out.write("\t                <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/");
      out.print(categoryNo);
      out.write('/');
      out.print(imgList.get(imgList.size()-1).getItemImageDefault());
      out.write("\" alt=\"상품정보이미지\">\r\n");
      out.write("\t            </section>\r\n");
      out.write("\t            <!-- 배송반품 -->\r\n");
      out.write("\t            <section id=\"details-infoShip\">\r\n");
      out.write("\t                <p>배송반품</p>\r\n");
      out.write("\t            </section>\r\n");
      out.write("\t            <!-- 이용후기 -->\r\n");
      out.write("\t            <section id=\"details-review\">\r\n");
      out.write("\t                <section id=\"writed-review\" class=\"list-wrapper\">\r\n");
      out.write("\t                    <h3 class=\"sr-only\">이용후기 리스트</h3>\r\n");
      out.write("\t                    <ul class=\"list-unstyled wishlist-inner\">\r\n");
      out.write("\t                        <li>\r\n");
      out.write("\t                            <section class=\"dtReview-header\">\r\n");
      out.write("\t                                <div class=\"star pull-left\">\r\n");
      out.write("\t                                    <span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t                                    <span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t                                    <span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t                                    <span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t                                    <span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t                                </div>\r\n");
      out.write("\t                                <div class=\"review-info pull-right\">\r\n");
      out.write("\t                                    <span class=\"review-writer\">uj9208</span>\r\n");
      out.write("\t                                    <span class=\"review-slash\"> | </span>\r\n");
      out.write("\t                                    <span class=\"review-date\">2019.12.22</span>\r\n");
      out.write("\t                                </div>\r\n");
      out.write("\t                            </section>\r\n");
      out.write("\t                            <section class=\"review-content\">\r\n");
      out.write("\t                                <div>\r\n");
      out.write("\t                                    <p>dolor voluptates delectus nemo voluptatem quam nisi impedit es delectus nemo voluptatem quam nisi impe ipsa minus unde, aliquam est? At sapiente necessitatibus corporis beatae?</p>\r\n");
      out.write("\t                                </div>\r\n");
      out.write("\t                                <div class=\"reviewImg-wrapper row\">\r\n");
      out.write("\t                                    <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/view-img1.jfif\" class=\"col-md-3\" alt=\"\">\r\n");
      out.write("\t                                    <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/view-img2.jfif\" class=\"col-md-3\" alt=\"\">\r\n");
      out.write("\t                                    <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/view-img3.jfif\" class=\"col-md-3\" alt=\"\">\r\n");
      out.write("\t                                </div>\r\n");
      out.write("\t                            </section>\r\n");
      out.write("\t                        </li>\r\n");
      out.write("\t                        <li>\r\n");
      out.write("\t                            <section class=\"dtReview-header\">\r\n");
      out.write("\t                                <div class=\"star pull-left\">\r\n");
      out.write("\t                                    <span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t                                    <span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t                                    <span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t                                    <span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t                                    <span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t                                </div>\r\n");
      out.write("\t                                <div class=\"review-info pull-right\">\r\n");
      out.write("\t                                    <span class=\"review-writer\">uj9208</span>\r\n");
      out.write("\t                                    <span class=\"review-slash\"> | </span>\r\n");
      out.write("\t                                    <span class=\"review-date\">2019.12.22</span>\r\n");
      out.write("\t                                </div>\r\n");
      out.write("\t                            </section>\r\n");
      out.write("\t                            <section class=\"review-content\">\r\n");
      out.write("\t                                <div>\r\n");
      out.write("\t                                    <p>dolor voluptates delectus nemo voluptatem quam nisi impedit es delectus nemo voluptatem quam nisi impe ipsa minus unde, aliquam est? At sapiente necessitatibus corporis beatae?</p>\r\n");
      out.write("\t                                </div>\r\n");
      out.write("\t                                <div class=\"reviewImg-wrapper row\">\r\n");
      out.write("\t                                    <!-- <img src=\"images/view-img1.jfif\" class=\"col-md-3\" alt=\"\">\r\n");
      out.write("\t                                    <img src=\"images/view-img2.jfif\" class=\"col-md-3\" alt=\"\">\r\n");
      out.write("\t                                    <img src=\"images/view-img3.jfif\" class=\"col-md-3\" alt=\"\"> -->\r\n");
      out.write("\t                                </div>\r\n");
      out.write("\t                            </section>\r\n");
      out.write("\t                        </li>\r\n");
      out.write("\t                    </ul>\r\n");
      out.write("\t                </section>\r\n");
      out.write("\t                <!-- 페이징바 -->\r\n");
      out.write("\t                <nav class=\"paging-bar text-center\">\r\n");
      out.write("\t                    <ul class=\"list-unstyled list-inline\">\r\n");
      out.write("\t                    <li>\r\n");
      out.write("\t                        <a href=\"#\" aria-label=\"Previous\">\r\n");
      out.write("\t                            <span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t                        </a>\r\n");
      out.write("\t                    </li>\r\n");
      out.write("\t                    <li class=\"cPage\"><a href=\"#\">1</a></li>\r\n");
      out.write("\t                    <li><a href=\"#\">2</a></li>\r\n");
      out.write("\t                    <li><a href=\"#\">3</a></li>\r\n");
      out.write("\t                    <li><a href=\"#\">4</a></li>\r\n");
      out.write("\t                    <li><a href=\"#\">5</a></li>\r\n");
      out.write("\t                    <li>\r\n");
      out.write("\t                        <a href=\"#\" aria-label=\"Next\">\r\n");
      out.write("\t                            <span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t                        </a>\r\n");
      out.write("\t                    </li>\r\n");
      out.write("\t                    </ul>\r\n");
      out.write("\t                </nav>\r\n");
      out.write("\t            </section>\r\n");
      out.write("\t            <!-- 상품QNA -->\r\n");
      out.write("\t            <section id=\"details-qna\">\r\n");
      out.write("\t                <div class=\"btn-wrapper\">\r\n");
      out.write("\t                    <button type=\"button\" id=\"btn-goQna\" class=\"btn-radius pull-right\">문의하기</button>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <section id=\"point-list\" class=\"list-wrapper\">\r\n");
      out.write("\t                    <h3 class=\"sr-only\">문의내역 리스트</h3>\r\n");
      out.write("\t                    <table class=\"text-center list-tbl\">\r\n");
      out.write("\t                        <thead>\r\n");
      out.write("\t                            <tr class=\"row\">\r\n");
      out.write("\t                                <th class=\"col-md-6 text-center\">문의내용</th>\r\n");
      out.write("\t                                <th class=\"col-md-2 text-center\">답변상태</th>\r\n");
      out.write("\t                                <th class=\"col-md-2 text-center\">작성자</th>\r\n");
      out.write("\t                                <th class=\"col-md-2 text-center\">작성일</th>\r\n");
      out.write("\t                            </tr>\r\n");
      out.write("\t                        </thead>\r\n");
      out.write("\t                        <tbody>\r\n");
      out.write("\t                        ");

	                        	if(qList!=null && !qList.isEmpty()){
	                        		for(ItemQna q: qList){
	                        
      out.write("\r\n");
      out.write("\t                            <tr class=\"row qna-header\">\r\n");
      out.write("\t                                <td class=\"col-md-6 qna-title\">\r\n");
      out.write("\t                                    <button type=\"button\" class=\"center-block\">");
      out.print(q.getItemQnaContent() );
      out.write("</button>\r\n");
      out.write("\t                                </td>\r\n");
      out.write("\t                                ");

	                                	if("Y".equals(q.getItemQnaAnsYn())){
	                                
      out.write("\r\n");
      out.write("\t                                \t\t<td class=\"col-md-2\">답변완료</td>\r\n");
      out.write("\t                                ");

	                                	}
	                                	else{
	                                
      out.write("\r\n");
      out.write("\t                                \t\t<td class=\"col-md-2\">답변대기</td>\r\n");
      out.write("\t                                ");

	                                	}
	                                
      out.write("\r\n");
      out.write("\t                                <td class=\"col-md-2\">");
      out.print(q.getMemberId() );
      out.write("</td>\r\n");
      out.write("\t                                <td class=\"col-md-2\">");
      out.print(q.getItemQnaDate() );
      out.write("</td>\r\n");
      out.write("\t                            </tr>\r\n");
      out.write("\t                            <tr class=\"row qna-view\">\r\n");
      out.write("\t                                <td colspan=\"4\" class=\"col-md-12\">\r\n");
      out.write("\t                                    <div class=\"q-wrapper\">\r\n");
      out.write("\t                                        <span class=\"q-title strong\">Q.</span>\r\n");
      out.write("\t                                        <p class=\"center-block\">");
      out.print(q.getItemQnaContent() );
      out.write("</p>\r\n");
      out.write("\t                                    </div>\r\n");
      out.write("\t                                    <div class=\"q-wrapper\">\r\n");
      out.write("\t                                        <span class=\"q-title strong\">A.</span>\r\n");
      out.write("\t                                        ");

			                                	if("Y".equals(q.getItemQnaAnsYn())){
			                                
      out.write("\r\n");
      out.write("\t\t\t                                \t\t<p class=\"center-block\">");
      out.print(qnaMap.get(q.getItemQnaNo()).getItemQnaAnsContent() );
      out.write("</p>\r\n");
      out.write("\t\t\t                                ");

			                                	}
			                                	else{
			                                
      out.write("\r\n");
      out.write("\t\t\t                                \t\t<p class=\"center-block\">답변대기 중입니다.</p>\r\n");
      out.write("\t\t\t                                ");

			                                	}
			                                
      out.write("\r\n");
      out.write("\t                                    </div>\r\n");
      out.write("\t                                </td>\r\n");
      out.write("\t                            </tr>\r\n");
      out.write("\t                        ");

		                        	}
		                        }
	                        	//상품Q&A가 없을 경우
	                        	else{
		                    
      out.write("\r\n");
      out.write("\t\t                    \t\t<tr><td colspan=\"4\">상품Q&A가 존재하지 않습니다.</td></tr>\r\n");
      out.write("\t\t                    ");

	                        	}
		                    
      out.write("\r\n");
      out.write("\t                        </tbody>\r\n");
      out.write("\t                    </table>\r\n");
      out.write("\t                </section> \r\n");
      out.write("\t                <!-- 페이징바 -->\r\n");
      out.write("\t                <nav class=\"paging-bar text-center\">\r\n");
      out.write("\t                    <ul class=\"list-unstyled list-inline\">\r\n");
      out.write("\t                        <li>\r\n");
      out.write("\t                            <a href=\"#\" aria-label=\"Previous\">\r\n");
      out.write("\t                                <span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t                            </a>\r\n");
      out.write("\t                        </li>\r\n");
      out.write("\t                        <li class=\"cPage\"><a href=\"#\">1</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">2</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">3</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">4</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">5</a></li>\r\n");
      out.write("\t                        <li>\r\n");
      out.write("\t                            <a href=\"#\" aria-label=\"Next\">\r\n");
      out.write("\t                                <span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t                            </a>\r\n");
      out.write("\t                        </li>\r\n");
      out.write("\t                    </ul>\r\n");
      out.write("\t                </nav>\r\n");
      out.write("\t            </section>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"col-md-1\"></div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<footer class=\"container-fluid\">\r\n");
      out.write("\t    <div class=\"line-style\"></div>\r\n");
      out.write("\t    <!-- first line -->\r\n");
      out.write("\t    <div id=\"footer-menu\" class=\"row\">\r\n");
      out.write("\t        <div class=\"col-md-3\">\r\n");
      out.write("\t            <header>회사소개</header>\r\n");
      out.write("\t            <ul class=\"list-unstyled\">\r\n");
      out.write("\t                <li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("\t                <li><a href=\"#\">정책안내</a></li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"col-md-3\">\r\n");
      out.write("\t            <header>고객서비스</header>\r\n");
      out.write("\t            <ul class=\"list-unstyled\">\r\n");
      out.write("\t                <li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("\t                <li><a href=\"#\">1:1문의</a></li>\r\n");
      out.write("\t                <li><a href=\"#\">주문현황</a></li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"col-md-3\">\r\n");
      out.write("\t            <header>문의하기</header>\r\n");
      out.write("\t            <p id=\"q-call\" class=\"lead\">1577-1577</p>\r\n");
      out.write("\t            <p id=\"q-email\" class=\"lead\">reflex@naver.com</p>\r\n");
      out.write("\t            <p>평일 10:00~18:00</p>\r\n");
      out.write("\t            <p>주말 및 공휴일 휴무</p>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"col-md-3\">\r\n");
      out.write("\t            <header>SNS</header>\r\n");
      out.write("\t            <ul class=\"list-unstyled\">\r\n");
      out.write("\t                <li><a href=\"#\">Facebook</a></li>\r\n");
      out.write("\t                <li><a href=\"#\">Instagram</a></li>\r\n");
      out.write("\t                <li><a href=\"#\">Twitter</a></li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <!-- second line -->\r\n");
      out.write("\t    <div id=\"about\" class=\"row\">\r\n");
      out.write("\t        <p class=\"eng\">re:flex</p>\r\n");
      out.write("\t        <p>대표:유찬호<span class=\"bar\"></span>사업자등록번호:419-87-00807<span class=\"bar\"></span>통신판매업신고:제 2017-서울마포-2273호</p>\r\n");
      out.write("\t        <p>주소: 서울특별시 마포구 동교동 203-43 4층<span class=\"bar\"></span>대표전화:1566-6813<span class=\"bar\"></span>FAX:070-7848-0818<span class=\"bar\"></span>이메일:reflex@naver.com</p>\r\n");
      out.write("\t        <p>개인정보관리책임자:유찬호</p>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div id=\"copyright\" class=\"line-style\"><span>ⓒ</span>2019 re:flex</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
>>>>>>> refs/heads/itemList-danbi
