/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-01-04 13:48:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jquery.json;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class json_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>ajax::jquery::json</title>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/jquery/jquery-3.4.1.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(()=>{\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write(".area{\r\n");
      out.write("\tborder: 1px solid red;\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\tmin-height: 50px;\r\n");
      out.write("\tmargin: 10px;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("}\r\n");
      out.write("table, td{\r\n");
      out.write("\tborder: 1px solid;\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("img{\r\n");
      out.write("\twidth:50px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>ajax::jquery::json</h1>\r\n");
      out.write("\t<h2>1.전체 회원 조회</h2>\r\n");
      out.write("\t<button id=\"btn1\">실행</button>\r\n");
      out.write("\t<div id=\"area1\" class=\"area\"></div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$(\"#btn1\").click(e=>{\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/jquery/json/member/selectAll\",\r\n");
      out.write("\t\t\ttype: \"get\",\r\n");
      out.write("\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\tsuccess: data =>{\r\n");
      out.write("\t\t\t\tconsole.log(data);//json문자열, javascript object//json parse처리가 된 값을 받았다.\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tlet $table = $(\"<table></table>\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(data).each((idx,member)=>{\r\n");
      out.write("\t\t\t\t\tlet html = \"<tr><td>\"+member.name+\"</td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td>\"+member.phone+\"</td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td><img src='");
      out.print(request.getContextPath());
      out.write("/images/\"+member.profile+\"'></td></tr>\"\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$table.append(html);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#area1\").html($table);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: (jqxhr, textStatus, errorThrown) =>{\r\n");
      out.write("\t\t\t\tconsole.log(\"ajax 처리실패.\",jqxhr, textStatus, errorThrown);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 실습문제 1: 이름검색 -->\r\n");
      out.write("\t<h2>2.회원 이름 검색 /jquery/json/member/searchName </h2>\r\n");
      out.write("\t<p>이름 일부만으로도 검색이 가능하게 한다.</p>\r\n");
      out.write("\t<input type=\"search\" id=\"searchName\" placeholder=\"이름\" />\r\n");
      out.write("\t<button id=\"btn2\">검색</button>\r\n");
      out.write("\t<div id=\"area2\" class=\"area\"></div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(\"#btn2\").click(e=>{\r\n");
      out.write("\t\t\tvar searchNameVal = $(\"#searchName\").val().trim();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/jquery/json/member/searchName\",\r\n");
      out.write("\t\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\t\tdata: {searchName: searchNameVal},\r\n");
      out.write("\t\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\t\tsuccess: data =>{\r\n");
      out.write("\t\t\t\t\tconsole.log(data);//json문자열, javascript object//json parse처리가 된 값을 받았다.\r\n");
      out.write("\t\t\t\t\tlet $table = $(\"<table></table>\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(data).each((idx,member)=>{\r\n");
      out.write("\t\t\t\t\t\tlet html = \"<tr><td>\"+member.name+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml += \"<td>\"+member.phone+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml += \"<td><img src='");
      out.print(request.getContextPath());
      out.write("/images/\"+member.profile+\"'></td></tr>\"\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t$table.append(html);\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#area2\").html($table);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: (jqxhr, textStatus, errorThrown) =>{\r\n");
      out.write("\t\t\t\t\tconsole.log(\"ajax 처리실패.\",jqxhr, textStatus, errorThrown);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 실습문제 2: 회원가입 -->\r\n");
      out.write("\t<h2>3.회원가입 /jquery/json/member/insertMember</h2>\r\n");
      out.write("\t<p>MemberSingletone.list에 회원을 추가하고, 추가된 목록을 리턴받아 #area3에 출력</p>\r\n");
      out.write("\t<input type=\"text\" id=\"name\" placeholder=\"이름\" /> <br /><br />\r\n");
      out.write("\t<input type=\"text\" id=\"phone\" placeholder=\"전화번호\" /> <br /><br />\r\n");
      out.write("\t<input type=\"text\" id=\"profile\" placeholder=\"프로필\" /> <br /><br />\r\n");
      out.write("\t<button id=\"btn3\">회원가입</button>\r\n");
      out.write("\t<div id=\"area3\" class=\"area\"></div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t//처리방식 : membersingletone에서 getlist로 리스트 가져와서\r\n");
      out.write("\t//input태그에서 작성한 파라미터를 통해 list에 추가하여 div#area3에 출력시킨다.\r\n");
      out.write("\t$(\"#btn3\").click(e=>{\r\n");
      out.write("\t\tvar $name = $(\"#name\").val().trim();\r\n");
      out.write("\t\tvar $phone = $(\"#phone\").val().trim();\r\n");
      out.write("\t\tvar $profile = $(\"#profile\").val().trim();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tconsole.log($name,$phone,$profile);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/jquery/json/member/insertMember\",\r\n");
      out.write("\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\tdata: {name: $name, phone: $phone, profile: $profile},\r\n");
      out.write("\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\tsuccess: data =>{\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tlet $table = $(\"<table></table>\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(data).each((idx,member)=>{\r\n");
      out.write("\t\t\t\t\tlet html = \"<tr><td>\"+member.name+\"</td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td>\"+member.phone+\"</td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td>\"+member.profile+\"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$table.append(html);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#area3\").html($table);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: (jqxhr,textStatus, errorThrown) =>{\r\n");
      out.write("\t\t\t\tconsole.log(\"ajax 처리실패\", jqxhr, textStatus, errorThrown);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tcomplete : function(data){\r\n");
      out.write("\t\t\t\t$(\"#name, #phone, #profile\").val(\"\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<h2>서버에 json문자열 보내기</h2>\r\n");
      out.write("\t<input type=\"text\" id=\"name2\" placeholder=\"이름\" /> <br /><br />\r\n");
      out.write("\t<input type=\"text\" id=\"phone2\" placeholder=\"전화번호\" /> <br /><br />\r\n");
      out.write("\t<input type=\"text\" id=\"profile2\" placeholder=\"프로필\" /> <br /><br />\r\n");
      out.write("\t<button id=\"btn4\">회원가입</button>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$(\"#btn4\").click(()=>{\r\n");
      out.write("\t\tvar member = {\r\n");
      out.write("\t\t\t\tname: $(\"#name2\").val(),\r\n");
      out.write("\t\t\t\tphone: $(\"#phone2\").val(),\r\n");
      out.write("\t\t\t\tprofile: $(\"#profile2\").val()\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar jsonMember = JSON.stringify(member);\r\n");
      out.write("\t\tconsole.log(jsonMember);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/jquery/json/member/insertMember2\",\r\n");
      out.write("\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\tdata: {jsonMember:jsonMember},\r\n");
      out.write("\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\tsuccess: data =>{\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: (jqxhr,textStatus, errorThrown) =>{\r\n");
      out.write("\t\t\t\tconsole.log(\"ajax 처리실패\", jqxhr, textStatus, errorThrown);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tcomplete : function(data){\r\n");
      out.write("\t\t\t\t$(\"#name2, #phone2, #profile2\").val(\"\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
