/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-01-04 10:44:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin.item;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.*;

public final class adminItemEnroll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1578106787049L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1577690548164L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\n");
      out.write("   \n");
      out.write("   \n");
      out.write("   ");
 
   		//로그인한 경우
   		Member memberLoggedIn= (Member)session.getAttribute("memberLoggedIn");

   
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <title>re:flex</title>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR:100,300,400,500,700,900&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Libre+Barcode+128+Text|Monoton|Permanent+Marker|Righteous|Seymour+One|Stalinist+One&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\"> <!-- 부트스트랩 -->\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/mypage.css\" rel=\"stylesheet\">\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.4.1.js\"></script>\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/header.js\"></script>\n");
      out.write("    \n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <header class=\"container-fluid navbar-fixed-top\">\n");
      out.write("        <div id=\"header-wrapper\" class=\"row\">\n");
      out.write("            <div id=\"logo\" class=\"col-md-4\">\n");
      out.write("                <h1 class=\"eng\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">re:flex</a></h1>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"search\" class=\"col-md-4\">\n");
      out.write("                <h2 class=\"sr-only\">상품 검색</h2>\n");
      out.write("                <form action=\"");
      out.print(request.getContextPath());
      out.write("/item/itemSearch\">\n");
      out.write("                    <button type=\"submit\" id=\"btn-search\" aria-label=\"search products\">\n");
      out.write("                        <span class=\"glyphicon glyphicon-search\" aria-hidden=\"true\"></span>\n");
      out.write("                    </button>\n");
      out.write("                    <input type=\"search\" name=\"search\" placeholder=\"검색\">\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"menu\" class=\"col-md-4\">\n");
      out.write("                <ul class=\"list-unstyled list-inline text-right\">\n");
      out.write("                    ");
if(memberLoggedIn==null){ 
      out.write("\n");
      out.write("                    <li class=\"login-hide\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberLogin\">로그인</a></li>\n");
      out.write("                    <li class=\"login-hide\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberEnroll\">회원가입</a></li>\n");
      out.write("                    ");
}
                    else{
                    
      out.write("\n");
      out.write("\n");
      out.write("\t                <li><span class=\"strong\">");
      out.print(memberLoggedIn.getMemberName());
      out.write("</span>님</li>                    \n");
      out.write("\n");
      out.write("\t                <li>\n");
      out.write("\t                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout\">로그아웃</a>\n");
      out.write("\t                </li>\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t");
if(memberLoggedIn !=null && !"admin".equals(memberLoggedIn.getMemberId())) {
      out.write("\n");
      out.write("                    <li>\n");
      out.write("                        <h2 class=\"sr-only\">장바구니</h2>\n");
      out.write("                        <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberCart?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\" aria-label=\"cart\"><span class=\"glyphicon glyphicon-shopping-cart\" aria-hidden=\"true\"></span></a>\n");
      out.write("                    </li>\n");
      out.write("                    ");
} 
      out.write("\n");
      out.write("                    <li>\n");
      out.write("                        <button type=\"button\"  id=\"btn-sidemenu\">\n");
      out.write("                            <span class=\"glyphicon glyphicon-list\" aria-hidden=\"true\"></span>\n");
      out.write("                        </button>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("                <!-- side menu -->\n");
      out.write("                <!-- level1 -->\n");
      out.write("                <div id=\"sidemenu-closeLayer\">\n");
      out.write("                <nav id=\"level1-sidemenu\" class=\"sidemenu-wrapper\">\n");
      out.write("                    <header></header>\n");
      out.write("                    <ul class=\"list-unstyled\">\n");
      out.write("                        <li id=\"recommended\" data-target=\"#level2-recommended\"><a href=\"#\">이럴 때 빌려봐<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\n");
      out.write("                        ");
 
                        	//관리자가 로그인한 경우
                        	if(memberLoggedIn != null && "admin".equals(memberLoggedIn.getMemberId())){ 
                        
      out.write("\n");
      out.write("                        \t<li id=\"adminPage\" data-target=\"#level2-adminPage\"><a href=\"#\">관리자페이지<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\n");
      out.write("\t\t\t\t\t\t");
 
							} 
                        	//로그인한 회원이 있는 경우 마이페이지 메뉴 
                        	else if(memberLoggedIn!=null && !("admin".equals(memberLoggedIn.getMemberId()))){
						
      out.write("\n");
      out.write("                        \t<li id=\"mypage\" data-target=\"#level2-mypage\"><a href=\"#\">마이페이지<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\n");
      out.write("                        ");

	                        }
                        	//로그인 안했으면 로그인, 회원가입 메뉴 보이게
							else{
                        
      out.write("\n");
      out.write("                        \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberLogin\">로그인</a></li>\n");
      out.write("                        \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberEnroll\">회원가입</a></li>\n");
      out.write("                        ");

							}
                        
      out.write("\n");
      out.write("                        <li><a href=\"#\">고객서비스(FAQ)</a></li>\n");
      out.write("                        <li><a href=\"#\">re:flex 소개</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("                <!-- level2: 이럴때빌려봐 -->\n");
      out.write("                <nav id=\"level2-recommended\" class=\"sidemenu-wrapper\">\n");
      out.write("                    <header class=\"text-center\">\n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\n");
      out.write("                        \t<span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\n");
      out.write("                              이럴 때 빌려봐\n");
      out.write("                        </button>\n");
      out.write("                    </header>\n");
      out.write("                    <ul class=\"list-unstyled\">\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT01\">반려동물과 함께 할 때</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT02\">육아할 때</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT03\">파티할 때</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT04\">운동할 때</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT05\">여행갈 때</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT06\">캠핑갈 때</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("                <!-- level2: 마이페이지 -->\n");
      out.write("                ");

                	if(memberLoggedIn != null){
                
      out.write("\n");
      out.write("                <nav id=\"level2-mypage\" class=\"sidemenu-wrapper\">\n");
      out.write("                    <header class=\"text-center\">\n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\n");
      out.write("                            <span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\n");
      out.write("                            마이페이지\n");
      out.write("                        </button>\n");
      out.write("                    </header>\n");
      out.write("                    <ul class=\"list-unstyled\">\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageOrderList?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">주문조회</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageWishlist?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">위시리스트</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageRentalIng?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">계약중인 렌탈</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageRentalFin?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">종료중인 렌탈</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypagePoint?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">포인트 확인</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageReview?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">이용후기 내역</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageOneToOne?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">1:1문의 내역</a></li>\n");
      out.write("                   \t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberUpdate?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">회원정보 수정</a></li> \n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberDelete?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">회원정보 탈퇴</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("                ");

                	}
                
      out.write("\n");
      out.write("\n");
      out.write("                \n");
      out.write("\n");
      out.write("                <nav id=\"level2-adminPage\" class=\"sidemenu-wrapper\">\n");
      out.write("                    <header class=\"text-center\">\n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\n");
      out.write("                            <span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\n");
      out.write("                            관리자페이지\n");
      out.write("                        </button>\n");
      out.write("                    </header>\n");
      out.write("                    <ul class=\"list-unstyled\">\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/itemEnroll\">상품등록</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/itemSearch\">상품조회</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/rentalList\">렌탈내역</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/orderList\">판매현황</a></li>\n");
      out.write("                        <li><a href=\"#\">배송관리</a></li>\n");
      out.write("                        <li><a href=\"#\">이용후기관리</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/member/memberQna\">1:1문의관리</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/member/memberSearch\">회원조회</a></li>\n");
      out.write("\n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </header>");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    .itemTitle{\r\n");
      out.write("        height: 46px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("    .height-45{\r\n");
      out.write("        height: 45px;\r\n");
      out.write("    }\r\n");
      out.write("    .m-0{\r\n");
      out.write("        margin: 0px !important;\r\n");
      out.write("    }\r\n");
      out.write("    .padding-left-25{\r\n");
      out.write("        padding-left: 25px !important;\r\n");
      out.write("        padding-top: 13px !important;\r\n");
      out.write("        padding-bottom: 13px !important;\r\n");
      out.write("    }\r\n");
      out.write("    .no-round-border{\r\n");
      out.write("        border-radius: 0;\r\n");
      out.write("    }\r\n");
      out.write("    .no-margin{\r\n");
      out.write("        margin: 0;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- page nav -->\r\n");
      out.write("<nav class=\"line-style page-nav\">\r\n");
      out.write("    <ul class=\"list-unstyled list-inline\">\r\n");
      out.write("        <li class=\"go-home\">\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">메인</a>\r\n");
      out.write("            <span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"go-boxmenu\">\r\n");
      out.write("            <a href=\"\">관리자페이지</a>\r\n");
      out.write("            <span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("        </li> \r\n");
      out.write("        <li>상품등록</li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 메인 컨텐츠 -->\r\n");
      out.write("            <div class=\"container-fluid contents\">\r\n");
      out.write("                <!-- 상품등록 - 메뉴제목 -->\r\n");
      out.write("                <div class=\"row itemTitle\">\r\n");
      out.write("                    <div class=\"col-md-8 col-sm-8 col-xs-8 col-md-offset-2 side-border\">\r\n");
      out.write("                        <h3>상품등록</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- 빈줄 하나 -->\r\n");
      out.write("                <div class=\"row height-45\"></div>\r\n");
      out.write("\r\n");
      out.write("                <!-- 상품등록 폼 -->\r\n");
      out.write("                <form action=\"");
      out.print(request.getContextPath());
      out.write("/admin/itemEnrollEnd\" class=\"p-0 col-md-8 col-sm-8 col-xs-8 col-md-offset-2\" method=\"post\" enctype=\"multipart/form-data\" id=\"itemEnroll\">\r\n");
      out.write("                    <!-- 상품등록 - 카테고리 -->\r\n");
      out.write("                    <div class=\"container-fluid\" id=\"category\">\r\n");
      out.write("                        <div class=\"subtitle border-all height-45\" >\r\n");
      out.write("                            <h4>카테고리</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"container-fluid border-no-top\">\r\n");
      out.write("                            <label class=\"radio-inline col-md-4 m-0 padding-left-25\">\r\n");
      out.write("                                <input type=\"radio\" name=\"category\" id=\"inlineCheckbox1\" value=\"CT01\" required> 반려동물과 함께할 때\r\n");
      out.write("                            </label>\r\n");
      out.write("                        \r\n");
      out.write("                            <label class=\"radio-inline col-md-4 m-0 padding-left-25 border-side\">\r\n");
      out.write("                                <input type=\"radio\" name=\"category\" id=\"inlineCheckbox2\" value=\"CT02\"> 육아할 때\r\n");
      out.write("                            </label>\r\n");
      out.write("\r\n");
      out.write("                            <label class=\"radio-inline col-md-4 m-0 padding-left-25\">\r\n");
      out.write("                                <input type=\"radio\" name=\"category\" id=\"inlineCheckbox3\" value=\"CT03\"> 행사, 파티할 때\r\n");
      out.write("                            </label>\r\n");
      out.write("                        \r\n");
      out.write("                            <label class=\"radio-inline col-md-4 m-0 padding-left-25 border-top\">\r\n");
      out.write("                                <input type=\"radio\" name=\"category\" id=\"inlineCheckbox1\" value=\"CT04\"> 운동할 때\r\n");
      out.write("                            </label>\r\n");
      out.write("\r\n");
      out.write("                            <label class=\"radio-inline col-md-4 m-0 padding-left-25 border-side border-top\">\r\n");
      out.write("                                <input type=\"radio\" name=\"category\" id=\"inlineCheckbox2\" value=\"CT05\"> 여행갈 때\r\n");
      out.write("                            </label>\r\n");
      out.write("\r\n");
      out.write("                            <label class=\"radio-inline col-md-4 m-0 padding-left-25 border-top\">\r\n");
      out.write("                                <input type=\"radio\" name=\"category\" id=\"inlineCheckbox3\" value=\"CT06\"> 캠핑갈 때\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"row height-45 border-side\"></div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- 상품등록 - 브랜드 -->\r\n");
      out.write("                    <div class=\"container-fluid\" id=\"item-name\">\r\n");
      out.write("                            <div class=\"subtitle border-all height-45\" >\r\n");
      out.write("                                <h4>브랜드</h4>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"container-fluid border-no-top height-45\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control shadow-none no-round-border height-45\" id=\"inputItemBrand\" name=\"itemBrand\" placeholder=\"브랜드를 입력하세요\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"row height-45 border-side\"></div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- 상품등록 - 상품명 -->\r\n");
      out.write("                    <div class=\"container-fluid\" id=\"item-name\">\r\n");
      out.write("                            <div class=\"subtitle border-all height-45\" >\r\n");
      out.write("                                <h4>상품명</h4>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"container-fluid border-no-top height-45\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control shadow-none no-round-border height-45\" id=\"inputItemName\" name=\"itemName\" placeholder=\"상품명을 입력하세요\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"row height-45 border-side\"></div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- 상품등록 - 상품가격 -->\r\n");
      out.write("                    <div class=\"container-fluid\" id=\"item-name\">\r\n");
      out.write("                        <div class=\"subtitle border-all height-45\" >\r\n");
      out.write("                            <h4>상품가격</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group border-no-top height-45 no-margin\">\r\n");
      out.write("                            <div class=\"input-group height-45\">\r\n");
      out.write("                                <div class=\"input-group-addon no-round-border\"><div class=\"glyphicon glyphicon-usd\"></div></div>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control shadow-none no-round-border height-45\" id=\"exampleInputAmount\" name=\"itemPrice\" placeholder=\"상품가격을 입력하세요\">\r\n");
      out.write("                                <div class=\"input-group-addon no-round-border no-margin\">원</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"row height-45 border-side\"></div>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- 상품등록 - 상품수량 -->\r\n");
      out.write("                    <div class=\"container-fluid\" id=\"item-name\">\r\n");
      out.write("                        <div class=\"subtitle border-all height-45\" >\r\n");
      out.write("                            <h4>상품수량</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"container-fluid border-no-top height-45\">\r\n");
      out.write("                            <input type=\"number\" class=\"form-control shadow-none no-round-border height-45\" id=\"inputItemStock\" name=\"itemStock\" placeholder=\"상품수량을 입력하세요\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"row height-45 border-side\"></div>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- 상품등록 - 상품 상세 설명-->\r\n");
      out.write("                    <div class=\"container-fluid\" id=\"item-name\">\r\n");
      out.write("                        <div class=\"subtitle border-all height-45\" >\r\n");
      out.write("                            <h4>상세 설명</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"container-fluid border-no-top\">\r\n");
      out.write("                            <textarea class=\"form-control shadow-none no-round-border \" rows=\"5\" id=\"inputItemDetail\" name=\"itemDesc\" placeholder=\"상품 상세 설명을 입력하세요\"></textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"row height-45 border-side\"></div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- 상품등록 - 이미지등록 -->\r\n");
      out.write("                    <div class=\"container-fluid\" id=\"item-name\">\r\n");
      out.write("                        <div class=\"subtitle border-all height-45\" >\r\n");
      out.write("                            <h4>이미지등록</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row container-fluid border-no-top\">\r\n");
      out.write("                            <div class=\"subtitle col-md-6\">대표이미지</div>\r\n");
      out.write("                            <input type=\"file\" class=\"shadow-none no-round-border height-45 col-md-6\" id=\"inputItemImageMain\" name=\"inputItemImageMain\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row container-fluid border-no-top\">\r\n");
      out.write("                            <div class=\"subtitle col-md-6\">서브이미지1</div>\r\n");
      out.write("                            <input type=\"file\" class=\"shadow-none no-round-border height-45 col-md-6\" id=\"inputItemImageSub1\" name=\"inputItemImageSub1\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row container-fluid border-no-top\">\r\n");
      out.write("                            <div class=\"subtitle col-md-6\">서브이미지2</div>\r\n");
      out.write("                            <input type=\"file\" class=\"shadow-none no-round-border height-45 col-md-6\" id=\"inputItemImageSub2\" name=\"inputItemImageSub2\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row container-fluid border-no-top\">\r\n");
      out.write("                            <div class=\"subtitle col-md-6\">서브이미지3</div>\r\n");
      out.write("                            <input type=\"file\" class=\"shadow-none no-round-border height-45 col-md-6\" id=\"inputItemImageSub3\" name=\"inputItemImageSub3\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row container-fluid border-no-top\">\r\n");
      out.write("                            <div class=\"subtitle col-md-6\">상세이미지</div>\r\n");
      out.write("                            <input type=\"file\" class=\"shadow-none no-round-border height-45 col-md-6\" id=\"inputItemImageDetail\" name=\"inputItemImageDetail\" required>\r\n");
      out.write("                        </div>  \r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- 상품등록 - 제출버튼 -->\r\n");
      out.write("                    <div class=\"container-fluid text-right\" id=\"item-submit\">\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-default col-md-offset-10 col-md-2\">상품 등록</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("\t\t\t$(document).ready(function(){\r\n");
      out.write("\t\t        $(\"button[type='submit']\").click(function(){\r\n");
      out.write("\t\t            var radioValue = $(\"input[name='category']:checked\").val();\r\n");
      out.write("\t\t            if(radioValue){\r\n");
      out.write("\t\t                document.getElementById(\"itemEnroll\").action = \"");
      out.print(request.getContextPath());
      out.write("/admin/itemEnrollEnd/\"+radioValue;\r\n");
      out.write("\t\t              \t\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t        });\r\n");
      out.write("\t\t    });\t\t\t\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("\t<footer class=\"container-fluid\">\n");
      out.write("\t    <div class=\"line-style\"></div>\n");
      out.write("\t    <!-- first line -->\n");
      out.write("\t    <div id=\"footer-menu\" class=\"row\">\n");
      out.write("\t        <div class=\"col-md-3\">\n");
      out.write("\t            <header>회사소개</header>\n");
      out.write("\t            <ul class=\"list-unstyled\">\n");
      out.write("\t                <li><a href=\"#\">이용약관</a></li>\n");
      out.write("\t                <li><a href=\"#\">정책안내</a></li>\n");
      out.write("\t            </ul>\n");
      out.write("\t        </div>\n");
      out.write("\t        <div class=\"col-md-3\">\n");
      out.write("\t            <header>고객서비스</header>\n");
      out.write("\t            <ul class=\"list-unstyled\">\n");
      out.write("\t                <li><a href=\"#\">FAQ</a></li>\n");
      out.write("\t                <li><a href=\"#\">1:1문의</a></li>\n");
      out.write("\t                <li><a href=\"#\">주문현황</a></li>\n");
      out.write("\t            </ul>\n");
      out.write("\t        </div>\n");
      out.write("\t        <div class=\"col-md-3\">\n");
      out.write("\t            <header>문의하기</header>\n");
      out.write("\t            <p id=\"q-call\" class=\"lead\">1577-1577</p>\n");
      out.write("\t            <p id=\"q-email\" class=\"lead\">reflex@naver.com</p>\n");
      out.write("\t            <p>평일 10:00~18:00</p>\n");
      out.write("\t            <p>주말 및 공휴일 휴무</p>\n");
      out.write("\t        </div>\n");
      out.write("\t        <div class=\"col-md-3\">\n");
      out.write("\t            <header>SNS</header>\n");
      out.write("\t            <ul class=\"list-unstyled\">\n");
      out.write("\t                <li><a href=\"#\">Facebook</a></li>\n");
      out.write("\t                <li><a href=\"#\">Instagram</a></li>\n");
      out.write("\t                <li><a href=\"#\">Twitter</a></li>\n");
      out.write("\t            </ul>\n");
      out.write("\t        </div>\n");
      out.write("\t    </div>\n");
      out.write("\t    <!-- second line -->\n");
      out.write("\t    <div id=\"about\" class=\"row\">\n");
      out.write("\t        <p class=\"eng\">re:flex</p>\n");
      out.write("\t        <p>대표:유찬호<span class=\"bar\"></span>사업자등록번호:419-87-00807<span class=\"bar\"></span>통신판매업신고:제 2017-서울마포-2273호</p>\n");
      out.write("\t        <p>주소: 서울특별시 마포구 동교동 203-43 4층<span class=\"bar\"></span>대표전화:1566-6813<span class=\"bar\"></span>FAX:070-7848-0818<span class=\"bar\"></span>이메일:reflex@naver.com</p>\n");
      out.write("\t        <p>개인정보관리책임자:유찬호</p>\n");
      out.write("\t    </div>\n");
      out.write("\t    <div id=\"copyright\" class=\"line-style\"><span>ⓒ</span>2019 re:flex</div>\n");
      out.write("\t</footer>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
